#!/usr/bin/python

import sys, getopt, argparse

# TODO: All these code should be in a parser block
parser = argparse.ArgumentParser()
parser.add_argument("--ciphers", help="SSL ciphers to use (SSL)")
parser.add_argument("--tlsv1.0", help="Use TLSv1.0 (SSL)", action="store_true")
parser.add_argument("--tlsv1.1", help="Use TLSv1.1 (SSL)", action="store_true")
parser.add_argument("--tlsv1.2", help="Use TLSv1.2 (SSL)", action="store_true")
parser.add_argument("-3", "--sslv3", help="Use SSLv3 (SSL)", action="store_true")
parser.add_argument("--crlfile", help="Get a CRL list in PEM format from the given file")
parser.add_argument("--cacert", help="CA certificate to verify peer against (SSL)")
parser.add_argument("--allow-stale-certs", type=int, help="Allow Stale Certs")
parser.add_argument("--pinnedcertificate", help="Pinned Certificate")
parser.add_argument("url", help="https url")
args = vars(parser.parse_args())

ciphers = ""
tls_version = 2
crlfile = ""
cacert = ""
allow_stale_certs = 0
pinnedcertificate = ""
url = ""
if args["url"]:
    url = args["url"]
if args["ciphers"]:
    ciphers = args["ciphers"]
if args["tlsv1.0"]:
    tls_version = 0
if args["tlsv1.1"]:
    tls_version = 1
if args["tlsv1.2"]:
    tls_version = 2
if args["sslv3"]:
    tls_version = 3
if args["crlfile"]:
    crlfile = args["crlfile"]
if args["cacert"]:
    cacert = args["cacert"]
if args["allow_stale_certs"]:
    allow_stale_certs = args["allow_stale_certs"]
if args["pinnedcertificate"]:
    pinnedcertificate = args["pinnedcertificate"]
